//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.Test.AuthRemote {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthRemote.IAuth")]
    public interface IAuth {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/Login", ReplyAction="http://tempuri.org/IAuth/LoginResponse")]
        Booking.Models.User Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/Login", ReplyAction="http://tempuri.org/IAuth/LoginResponse")]
        System.Threading.Tasks.Task<Booking.Models.User> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/CreateLogin", ReplyAction="http://tempuri.org/IAuth/CreateLoginResponse")]
        bool CreateLogin(string email, string password, string firstname, string lastname, string address, int zipcode, long phonenumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuth/CreateLogin", ReplyAction="http://tempuri.org/IAuth/CreateLoginResponse")]
        System.Threading.Tasks.Task<bool> CreateLoginAsync(string email, string password, string firstname, string lastname, string address, int zipcode, long phonenumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthChannel : Booking.Test.AuthRemote.IAuth, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthClient : System.ServiceModel.ClientBase<Booking.Test.AuthRemote.IAuth>, Booking.Test.AuthRemote.IAuth {
        
        public AuthClient() {
        }
        
        public AuthClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Booking.Models.User Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<Booking.Models.User> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public bool CreateLogin(string email, string password, string firstname, string lastname, string address, int zipcode, long phonenumber) {
            return base.Channel.CreateLogin(email, password, firstname, lastname, address, zipcode, phonenumber);
        }
        
        public System.Threading.Tasks.Task<bool> CreateLoginAsync(string email, string password, string firstname, string lastname, string address, int zipcode, long phonenumber) {
            return base.Channel.CreateLoginAsync(email, password, firstname, lastname, address, zipcode, phonenumber);
        }
    }
}
